# this is Docker file for install opendds by autobuild 
FROM ubuntu:latest
MAINTAINER Yong Fu fuy@ociweb.com

RUN apt-get update -q
RUN apt-get install subversion perl build-essential curl -y
ADD scripts /scripts

# Install OpenDDS
# Readme : http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/DDS/docs/INSTALL
RUN cd /opt && svn co svn://svn.dre.vanderbilt.edu/DOC/DDS/trunk DDS
